name: CI
on: [push]
jobs:
  build:
    name: Build, lint, test and release on Node 16 
    runs-on: ubuntu-latest
    steps:
      - name: Setup git user information 
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 16 
        uses: actions/setup-node@v1
        with:
          node-version: 16 

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Coverage 
        run: npx codecov -f coverage/*.json 

      - name: Pack Inspect
        run: yarn pack:inspect
    
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

      - name: Build Example
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn build:example 

      - name: Deploy Example
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
